### ISSUE TITLE
xsdata missing

### ISSUE THREAD

**Issue by kwollw** [maxblan/socha-python-client#34]
## Description

creating and running a client as described in this repo results in an runtime error (missing module xsdata)

## Environment

-   Python version: 3.11.2
-   Operating System: Debian 12 
-   Version of the Python SoCha Client: 2.0.0

## Reproduction Steps

python3 -m venv sc24

source sc24/bin/activate

pip install socha-2.0.0-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl

File pus-client.py:
```
from socha import IClientHandler, Starter

class Logic(IClientHandler):
    from socha import GameState, Move
    gameState: GameState

    def calculate_move(self) -> Move:
        possibleMoves = self.gameState.possible_moves
        return possibleMoves[0]

    def on_update(self, state: GameState):
        self.gameState = state

if __name__ == "__main__":
  Starter(Logic())
```
python  pus-client.py

==>   ModuleNotFoundError: No module named 'xsdata'

## Solution:

pip install xsdata

pip list

```
Package           Version
----------------- -------
pip               23.0.1
setuptools        66.1.1
socha             2.0.0
typing_extensions 4.8.0
xsdata            23.8
```

**Comment by maxblan** [comment]
Thank you for this finding. The problem was related to a missing specification of the dependencies.
