### ISSUE TITLE
socha 2.0.1 incomplete

### ISSUE THREAD

**Issue by kwollw** [maxblan/socha-python-client#36]
## Description

in venv:
pip install socha => socha 2.0.1 

socha is incomplete, from socha install  IClientHandler, ... or from socha install * does not find to the classes expected in module socha

## Environment

-   Python version: 3.11.2
-   Operating System: Debian 12 
-   Version of the Python SoCha Client: 2.0.1

**Comment by maxblan** [comment]
Many thanks for the tip. In fact, everything is still there, but the imports in __init__.py had to be removed (f8d397ab1e23750d59f39733d43003f0da3476f4), otherwise the code completion of the IDEs would get mixed up. Unfortunately, the logic.py was forgotten to be adapted accordingly.
