### ISSUE TITLE
wrong Link to readthedos 

### ISSUE THREAD

**Issue by kwollw** [maxblan/socha-python-client#38]
In the readme the link to readthedocs should be corrected: 

https://socha-python-client.readthedocs.io/en/latest/

**Comment by maxblan** [comment]
RTD has been updated.

**Comment by kwollw** [comment]
Not solved yet (wrong link):

Hey there! To help you out, it's best to start by checking out the [documentation for this client](https://socha-python-client.readthedocs.readthedocs.io/en/latest/) before you ask any questions or open an issue. It'll provide you with some helpful information!
