### ISSUE TITLE
setuptools missing

### ISSUE THREAD

**Issue by kwollw** [maxblan/socha-python-client#40]
## Description

creating and running a client as described in this repo results in an runtime error due to missing module setuptools

## Environment

-   Python version: 3.11.2
-   Operating System: Debian 12 
-   Version of the Python Socha Client: 2.0.4

## Reproduction Steps

python3 -m venv sc24

source sc24/bin/activate

pip install socha

pip list

```
Package           Version
----------------- -------
pip               23.0.1
socha             2.0.4
xsdata            22.9
```

starting our Client:

python  pus-client.py

==>   ModuleNotFoundError: No module named 'pkg_resources'

## Solution:

pip install setuptools

**Comment by maxblan** [comment]
This is caused by a broken/missing Python setuptools package. Since this is a general package of Python, I do not consider including it in the requirements of `socha` at this time.

However, I will note this in the documentation in case other people encounter this problem.
