### ISSUE TITLE
Board#.find_nearest_field_types does not search beyond adjacent fields

### ISSUE THREAD

**Issue by kwollw** [maxblan/socha-python-client#42]
## Description

When searching for a field of certain type (e.g. Passenger) Board#.find_nearest_field_types returns an empty List if the field of certain type is more than one field away.

## Environment

-   Python version: 3.11.2
-   Operating System: Debian 12 
-   Version of the Python SoCha Client: 2.0.6

## Expected Behavior

remote fields of a certain type will be found by Board#.find_nearest_field_types

## Actual Behavior

fields of a certain type will only be found by Board#.find_nearest_field_types if they are adjacent fields

## Reproduction Steps (if applicable)

Run this function to observe the bug:

```python    
def analyse_board(self):
     gs = self.gameState
     for ft in [FieldType.Water, FieldType.Island, FieldType.Passenger, FieldType.Goal]:
         for c in gs.board.find_nearest_field_types(gs.current_ship.position, ft):
             print(ft, c.coordinates())
```

**Comment by maxblan** [comment]
Hi, thank you very much for the tip. I was able to reproduce the problem and could find a solution. I'll publish a new version soon.

**Comment by kwollw** [comment]
I would apreciate to have version 2.0.7 tomorrow, as it will be our last class before Christmas.
