### ISSUE TITLE
Board#.find_nearest_field_types() causes computer to freeze

### ISSUE THREAD

**Issue by kwollw** [maxblan/socha-python-client#44]
## Description

After calling Board#.find_nearest_field_types() computer freezes after some time.  The method exits with returning a list of multiple coordinates of the same field where only one element is expected. Thereafter the computer freezes within next minutes.

Is the method recursively concurrent? I have not analyzed the Rust code and have no concrete hypothesis about the cause of the freeze

## Environment

-   Python version: 3.11.2
-   Operating System: Debian 12 
-   Version of the Python SoCha Client: 2.0.7

## Expected Behavior

No freeze

## Actual Behavior

see description

## Reproduction Steps (if applicable)

Run this function to observe the bug:
```python
    def analyse_board(self):
        gs = self.gameState
        print('next passenger fields:')
        for c in gs.board.find_nearest_field_types(gs.current_ship.position, FieldType.Passenger):
            print(c.coordinates())
```

**Comment by kwollw** [comment]
The freezing could not be reproduced yet, the problem of multiples in Coordinates list remain

**Comment by maxblan** [comment]
No, there is no recursion or concurrency in that method. If the freeze doesn't happen again I will ignore this for now.

The issue with multiple entries of the same instance is interesting. I wasn't able to create this phenomenon in my unit test.
Could you please add a picture of the game field, if you use the GUI? A output of a print would also work.

**Comment by maxblan** [comment]
Regarding your crash, I may found a potential issue with the method. I didn't implemented a hard break if no field with the correct  field type is in the board, which causes an infinite loop.
I'm sorry for this issue and I'll publish a fix in the next hour.

**Comment by maxblan** [comment]
I've released the new version and it is currently in the pipeline. In the next 5 minutes it should be available via pip.
