### ISSUE TITLE
Ship does not track number of collected passengers

### ISSUE THREAD

**Issue by kwollw** [maxblan/socha-python-client#47]
## Description

After collecting a passenger Ship#.passengers remains 0

## Environment

-   Python version: 3.11.2
-   Operating System: Debian 12 
-   Version of the Python SoCha Client: 2.1.0 (cannot be updated due to other issue in socha 2.1.1)

## Expected Behavior

After collecting a passenger Ship#.passengers should be incremented by 1

## Actual Behavior

After collecting a passenger Ship#.passengers remains 0

**Comment by maxblan** [comment]
Thank you for submitting the report. I will thoroughly investigate the error and release an updated version on Sunday to resolve the issue.

**Comment by kwollw** [comment]
The problem still remains:

After ship has collected passenger:

print('current ship passengers:',self.gameState.current_ship.passengers)
print('other ship passengers:',self.gameState.other_ship.passengers)

output:

current ship passengers: 0
other ship passengers: 0
